// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9h0wvrc6OabIUPdreq3284bLNkyWG06E',
    appId: '1:598778364541:web:363c6adf4e04e9d62b6714',
    messagingSenderId: '598778364541',
    projectId: 'chat-ba313',
    authDomain: 'chat-ba313.firebaseapp.com',
    storageBucket: 'chat-ba313.firebasestorage.app',
    measurementId: 'G-ZESPGHSYJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8rVbGriJFyNlXEXGvln2TntWqMaD1d0',
    appId: '1:598778364541:android:1df9d91f9c4297342b6714',
    messagingSenderId: '598778364541',
    projectId: 'chat-ba313',
    storageBucket: 'chat-ba313.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlrEiS7tIOKYtjtGi5_kpvgRi7WBP_3b4',
    appId: '1:598778364541:ios:57b9f8035ec19eca2b6714',
    messagingSenderId: '598778364541',
    projectId: 'chat-ba313',
    storageBucket: 'chat-ba313.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9h0wvrc6OabIUPdreq3284bLNkyWG06E',
    appId: '1:598778364541:web:64d58ffc4858ad172b6714',
    messagingSenderId: '598778364541',
    projectId: 'chat-ba313',
    authDomain: 'chat-ba313.firebaseapp.com',
    storageBucket: 'chat-ba313.firebasestorage.app',
    measurementId: 'G-TF1ZKT4847',
  );
}
